### ISSUE TITLE
UI improvement: is there any reason to keep the bottom centre arrow?

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#145]
![Captura de tela 2022-09-17 211839](https://user-images.githubusercontent.com/73800734/190880482-82566db8-6c67-4d21-92c3-0d4c270a96c9.png)
There's a insignificant increase in the amount of content displayed after clicking the arrow. Wouldn't it be better to just get rid of the arrow? Alternatively you could make the arrow more useful by significantly increasing the amount of displayed content and remembering this setting after closing the window.

**Comment by martinet101** [comment]
You mean like removing the arrow when there are no installs?

**Comment by ppvnf** [comment]
> You mean like removing the arrow when there are no installs?

Yes. Also, if there are installs I wonder what's the point. It only makes sense if the install fails, since successful installs are automatically dismissed (too quickly IMO). Even in this case I think a X to clear every install would be more useful than the arrow to hide them.

So, my suggestions are:

1- remove or hide arrow if there are no installs
2 - make dismissal of successful installs either slower or manual only
3 - replace the arrow with a X to dismiss everything instead of hiding everything (you could also keep both options)

**Comment by martinet101** [comment]
Hi, i've been rethinking about those features:

> * [ ] make dismissal of successful installs either slower or manual only
> * [ ]   replace the arrow with a X to dismiss everything instead of hiding everything (you could also keep both options)

I don't think dismissal should manual, because:
1. This is the list of the apps that are being installed.
2. When an app gets installed successfully, a notification is thrown, and it should remain in your action center.

About replacing the arrow for an X, the thing is not about _discarding_ current installs, but rather hiding them if they interfiere with the app current operation, so I don't think it makes much sense
