### ISSUE TITLE
Feature Request: git fetch/ git repo

### ISSUE THREAD

**Issue by NotNullBool** [martinet101/WingetUI#151]
Git intergration into wingetui? It would be nice to be notification updates for my applications in the same place. For example Ive been using stable diffusion lately it would be nice to be notified when it updates from winget.

**Comment by martinet101** [comment]
I don't understand what you mean. Git is not a package manager, isn't it?

**Comment by NotNullBool** [comment]
No its not i just figured it would be nice to add git url to the wingetui. Then be able to fetch git for an update or to pull to update that file since some applications use github as a distribution as well. However I feel this could be considered out of scope for this project.

**Comment by martinet101** [comment]
Honestly, I don't know, since git does not provide the structure that a package manager has.

I mean:
from a package manager you can search, install/update and uninstall, while from git you can only update and install. (no search or remove)

I'm sorry mate, but i don't think git will appear in WingetUI
