### ISSUE TITLE
scoop virustotal command

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#160]
@martinet101, I've never heard of anyone downloading malware through scoop, but I would like a second opinion on this. Do you think the `scoop virustotal` command is useless? I know Winget already scans for malware, but I couldn't find any information about scoop. Also, I am not sure it would be possible to implement this on WingetUI since it's necessary to configure an api key. In my mind it would work like this: select a package you want to install (maybe also update) and right-click an option like "Scan with VirusTotal" to scan it for malware.

**Comment by martinet101** [comment]
I have seen it in the scoop API, but (as far as I understand), it was meant for custom/third party buckets, not for the official ones (because they have been verified.)

I don't think this would be an easy thing to do, neither to implement nor to use (it would require api keys and other things that most users wouldn't want to mess with)

And honestly, I don't think most users would want to use this feature, because in the really strange case that an app gets infected/the dev publishes a suspicious package, Windows Defender antivirus would immediately block the file, preventing any kind system infection
