### ISSUE TITLE
(Beta) Remove "system language"?

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#280]
Current behavior when running storeEngine.py, PT-BR (System language) is selected by default, instead of the option "System language".  There are two options to solve this: remove the option "System language" or make it the default option (in this case it could also be translatable)

![Captura de tela 2022-10-15 214237](https://user-images.githubusercontent.com/73800734/196013142-5187791a-61c6-4b71-8255-a26a8a98b191.png)

By the way, why am I seeing only the translated percentage of Portuguese?

**Comment by martinet101** [comment]
system language will be selected only when the language of the system is not available in wingetUI, leading to an unset language (fallback to english) until this language gets added to WingetUI.

The percentages are only shown on unfinished translations (in this case is because i haven't pushed the updated jsons yet)
