### ISSUE TITLE
[FEATURE REQUEST] Python 3.11

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#334]
I just noticed that a new Python version was released. It seems to make apps run at least 10% faster, but I am not a programmer so I don't know how hard it would be to apply this performance boost to WingetUI

**Comment by martinet101** [comment]
Well, WingetUI does not rely on python-processing power, but rather in winget and scoop speeds, so this improvement wouldn't really increase WingetUI speeds. 

Also, i'd like to furhter test compatibiilty, because ea new version is knwn to break pyinstaller in some sort of way, so python3.11 will not be in WingetUI _yet_

**Comment by martinet101** [comment]
WingetUI 1.5.0 runs on Python3.11
