### ISSUE TITLE
360 antivirus software reports Trojans

### ISSUE THREAD

**Issue by qidouhai** [martinet101/WingetUI#42]

**Comment by martinet101** [comment]
Can you please try scanning ElevenClock with VirusTotal?

**Comment by martinet101** [comment]
(it is an online antivirus)

**Comment by Zazou49** [comment]
Kaspersky Total Security (21.3.10.39) also found a flase positive when installing : 

Trojan: PDM:Trojan.Win32.Bazon.a
Path: c:\users\alex\appdata\local\programs\wingetui\install_scoop.cmd

**Comment by martinet101** [comment]
Those must be false positives.

Since heuristics detected silent installing of software, they might have flagged it. 

This is what virustotal says:
1st file: https://www.virustotal.com/gui/file/11c76bcf9e9d6be85ef0004caeec838f1a0e9b4f53952733fcd13a7d1e710dba
3rd file: https://www.virustotal.com/gui/file/b7ce596205d5cc30a64e210a1b2849a21a020cedb2aa6b6f06cfc9b78cd0a7a4

The second file is a temp file generated by the installer, so i can't scan it and post he results.
