### ISSUE TITLE
Feature request: Ability to turn off auto-update

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#50]
For compatibility with package managers like Scoop that handle app updates on their own.

**Comment by martinet101** [comment]
I guess turning off updates could be done, but upgrading WingetUI from WingetUI itself would fail/hang

**Comment by ppvnf** [comment]
I am happy there's a new version, but unfortunately Kaspersky AV says auto-update is a trojan. I know it's very likely a false positive since AVs are getting more aggressive lately, but it's still annoying. Maybe showing a pop up when there's a new version available would be better. I personally disable all auto updates and run "scoop update *" once a week

**Comment by martinet101** [comment]
Allright, i'll add a switch to disable updates

**Comment by martinet101** [comment]
Done!
