### ISSUE TITLE
[FEATURE REQUEST] Show info for MSStore packages

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#511]
I said in https://github.com/martinet101/WingetUI/issues/502 that it was not possible to get info for MSStore packages. But after giving some thought I might have figured out a way using the id (or at least part of it). For example the MSStore package "NVIDIACorp.NVIDIAControlPanel_56…":

1- strip "NVIDIACorp." and "_56…"
2- convert from CamelCase "NVIDIAControlPanel" to NVIDIA Control Panel (not case sensitive)
3- use command `winget show "nvidia control panel"`

**Comment by ppvnf** [comment]
If this is indeed possible you would also have to specify the source, since some packages might also be available in winget. For example: `winget show "Microsoft Edge" --source msstore`

**Comment by martinet101** [comment]
For the moment, since the mstore is quite broken, i would prefer not to include this for the moment.

I already tested that, but some packages it does not work, since they being "Microsoft Store" is not actually true, but rather the truth is that they were installed through .appx/.msix installers, but not necessarily microsoft store, then they might not be published on winget
